version: '3'

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: InnoCPC
      POSTGRES_USER: InnoCPC
      POSTGRES_PASSWORD: InnoCPC
    volumes:
      - "InnoCPC:/var/lib/postgresql/data/"

volumes:
  InnoCPC: